# Site settings
title: Gentle Fitness
email: samantha@gentlefitness.co.uk
description: >
    Gentle Fitness is the home of fitness expert Samantha Crease from Bristol, UK.
    Gentle Fitness offers a range of exercise classes, massage treatments and
    other fitness and leisure services including swimming lessons.
baseurl: ""
url: "http://gentlefitness.co.uk"
owner_fullname: Samantha Crease
owner_firstname: Samantha

twitter_username: >
    @fitnesssammie
twitter_url: https://twitter.com/fitnesssammie
facebook_username: bristolgentlefitness
facebook_url: https://www.facebook.com/bristolgentlefitness
github_username:  jekyll

# Build settings
markdown: kramdown
